### ISSUE TITLE
Fix WIB2Frame format

### ISSUE THREAD

**Issue by jmcarcell** [DUNE-DAQ/detdataformats#22]
At least one of the setters or getters is not working correctly, for example this code:
``` cpp
  WIB2Frame fr;
  fr.set_adc(25, 25);
  std::cout << fr.get_adc(25) << std::endl;
```
returns different values when executing several times, sometimes 25, sometimes a different number. Setting the values by FEMB also gives different values each time:
``` cpp
  fr.set_u(0, 25, 10);
  std::cout << fr.get_u(0, 25) << std::endl;
```
I executed this by copying the format and compiling in my local machine but creating a test that does this also reproduces the issue (this time always getting a different value from the one that was set). This also happens using the latest version in the 2.11.x patch branch

**Comment by roland-sipos** [comment]
Linked merged PR, closing ticket.
