### ISSUE TITLE
The setter for DAPHNE frames is wrong

### ISSUE THREAD

**Issue by jmcarcell** [DUNE-DAQ/detdataformats#26]
Same issue as for the WIB2Frame setter and same fix

**Comment by roland-sipos** [comment]
Fixed in https://github.com/DUNE-DAQ/detdataformats/pull/20

**Comment by jmcarcell** [comment]
This is **not** fixed yet, this is DAPHNE frames :)

**Comment by roland-sipos** [comment]
Is it still wrong? Moved it back to triage.
